modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-ND 3.0"
issueTrackerURL="https://github.com/valeriotor/Beyond-The-Veil/issues"

[[mods]]
modId="beyondtheveil"
version="${file.jarVersion}"
displayName="Beyond The Veil"
logoFile="examplemod.png"
credits="Azanor, for Baubles. The creators on FreeSound.org (listed in the sounds folder under CREDITS). The people on the forge forums for asking and answering questions." #optional
authors="valeriotor"
description='''
A story driven Minecraft mod inspired by the writings of H.P. Lovecraft, and other works based on the author.
'''

[[dependencies.beyondtheveil]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyondtheveil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyondtheveil]]
    modId="curios"
    mandatory=true
    versionRange="[5.12.0+1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyondtheveil]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.7,)"
    ordering="NONE"
    side="BOTH"