package com.valeriotor.beyondtheveil.lib;

import com.valeriotor.beyondtheveil.Registration;
import com.valeriotor.beyondtheveil.fluid.SurgicalFluidType;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Tuple;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.FluidType;
import net.minecraftforge.fluids.ForgeFlowingFluid;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class BTVFluids {
    private static final DeferredRegister<FluidType> FLUID_TYPES = DeferredRegister.create(ForgeRegistries.Keys.FLUID_TYPES, References.MODID);
    private static final DeferredRegister<Fluid> FLUIDS = DeferredRegister.create(ForgeRegistries.FLUIDS, References.MODID);

    public static void init(IEventBus bus) {
        FLUID_TYPES.register(bus);
        FLUIDS.register(bus);
    }


    // TODO rename this into Serum X49B8 - Strength (and all subsequent vanilla effects turned Arsenal effects as well)
    public static final RegistryObject<FluidType> MOVEMENT_SPEED_SERUM_FLUID_TYPE = FLUID_TYPES.register("movement_speed_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/movement_speed_serum_still"), new ResourceLocation(References.MODID, "block/fluids/movement_speed_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/movement_speed_serum_overlay"), 3402751));
    public static final RegistryObject<FluidType> MOVEMENT_SLOWDOWN_SERUM_FLUID_TYPE = FLUID_TYPES.register("movement_slowdown_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/movement_slowdown_serum_still"), new ResourceLocation(References.MODID, "block/fluids/movement_slowdown_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/movement_slowdown_serum_overlay"), 9154528));
    public static final RegistryObject<FluidType> DIG_SPEED_SERUM_FLUID_TYPE = FLUID_TYPES.register("dig_speed_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/dig_speed_serum_still"), new ResourceLocation(References.MODID, "block/fluids/dig_speed_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/dig_speed_serum_overlay"), 14270531));
    public static final RegistryObject<FluidType> DIG_SLOWDOWN_SERUM_FLUID_TYPE = FLUID_TYPES.register("dig_slowdown_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/dig_slowdown_serum_still"), new ResourceLocation(References.MODID, "block/fluids/dig_slowdown_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/dig_slowdown_serum_overlay"), 4866583));
    public static final RegistryObject<FluidType> DAMAGE_BOOST_SERUM_FLUID_TYPE = FLUID_TYPES.register("damage_boost_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/damage_boost_serum_still"), new ResourceLocation(References.MODID, "block/fluids/damage_boost_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/damage_boost_serum_overlay"), 16762624));
    public static final RegistryObject<FluidType> HEAL_SERUM_FLUID_TYPE = FLUID_TYPES.register("heal_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/heal_serum_still"), new ResourceLocation(References.MODID, "block/fluids/heal_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/heal_serum_overlay"), 16262179));
    public static final RegistryObject<FluidType> HARM_SERUM_FLUID_TYPE = FLUID_TYPES.register("harm_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/harm_serum_still"), new ResourceLocation(References.MODID, "block/fluids/harm_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/harm_serum_overlay"), 11101546));
    public static final RegistryObject<FluidType> JUMP_SERUM_FLUID_TYPE = FLUID_TYPES.register("jump_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/jump_serum_still"), new ResourceLocation(References.MODID, "block/fluids/jump_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/jump_serum_overlay"), 16646020));
    public static final RegistryObject<FluidType> CONFUSION_SERUM_FLUID_TYPE = FLUID_TYPES.register("confusion_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/confusion_serum_still"), new ResourceLocation(References.MODID, "block/fluids/confusion_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/confusion_serum_overlay"), 5578058));
    public static final RegistryObject<FluidType> REGENERATION_SERUM_FLUID_TYPE = FLUID_TYPES.register("regeneration_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/regeneration_serum_still"), new ResourceLocation(References.MODID, "block/fluids/regeneration_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/regeneration_serum_overlay"), 13458603));
    public static final RegistryObject<FluidType> DAMAGE_RESISTANCE_SERUM_FLUID_TYPE = FLUID_TYPES.register("damage_resistance_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/damage_resistance_serum_still"), new ResourceLocation(References.MODID, "block/fluids/damage_resistance_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/damage_resistance_serum_overlay"), 9520880));
    public static final RegistryObject<FluidType> FIRE_RESISTANCE_SERUM_FLUID_TYPE = FLUID_TYPES.register("fire_resistance_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/fire_resistance_serum_still"), new ResourceLocation(References.MODID, "block/fluids/fire_resistance_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/fire_resistance_serum_overlay"), 16750848));
    public static final RegistryObject<FluidType> WATER_BREATHING_SERUM_FLUID_TYPE = FLUID_TYPES.register("water_breathing_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/water_breathing_serum_still"), new ResourceLocation(References.MODID, "block/fluids/water_breathing_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/water_breathing_serum_overlay"), 10017472));
    public static final RegistryObject<FluidType> INVISIBILITY_SERUM_FLUID_TYPE = FLUID_TYPES.register("invisibility_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/invisibility_serum_still"), new ResourceLocation(References.MODID, "block/fluids/invisibility_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/invisibility_serum_overlay"), 16185078));
    public static final RegistryObject<FluidType> BLINDNESS_SERUM_FLUID_TYPE = FLUID_TYPES.register("blindness_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/blindness_serum_still"), new ResourceLocation(References.MODID, "block/fluids/blindness_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/blindness_serum_overlay"), 2039587));
    public static final RegistryObject<FluidType> NIGHT_VISION_SERUM_FLUID_TYPE = FLUID_TYPES.register("night_vision_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/night_vision_serum_still"), new ResourceLocation(References.MODID, "block/fluids/night_vision_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/night_vision_serum_overlay"), 12779366));
    public static final RegistryObject<FluidType> HUNGER_SERUM_FLUID_TYPE = FLUID_TYPES.register("hunger_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/hunger_serum_still"), new ResourceLocation(References.MODID, "block/fluids/hunger_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/hunger_serum_overlay"), 5797459));
    public static final RegistryObject<FluidType> WEAKNESS_SERUM_FLUID_TYPE = FLUID_TYPES.register("weakness_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/weakness_serum_still"), new ResourceLocation(References.MODID, "block/fluids/weakness_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/weakness_serum_overlay"), 4738376));
    public static final RegistryObject<FluidType> POISON_SERUM_FLUID_TYPE = FLUID_TYPES.register("poison_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/poison_serum_still"), new ResourceLocation(References.MODID, "block/fluids/poison_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/poison_serum_overlay"), 8889187));
    public static final RegistryObject<FluidType> WITHER_SERUM_FLUID_TYPE = FLUID_TYPES.register("wither_serum_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/wither_serum_still"), new ResourceLocation(References.MODID, "block/fluids/wither_serum_flow"), new ResourceLocation(References.MODID, "block/fluids/wither_serum_overlay"), 7561558));
    public static final RegistryObject<FluidType> MEMORY_HORMONES_FLUID_TYPE = FLUID_TYPES.register("memory_hormones_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/memory_hormones_still"), new ResourceLocation(References.MODID, "block/fluids/memory_hormones_flow"), new ResourceLocation(References.MODID, "block/fluids/memory_hormones_overlay"), 0xFF007F7F));
    public static final RegistryObject<FluidType> OBEDIENCE_HORMONES_FLUID_TYPE = FLUID_TYPES.register("obedience_hormones_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/obedience_hormones_still"), new ResourceLocation(References.MODID, "block/fluids/obedience_hormones_flow"), new ResourceLocation(References.MODID, "block/fluids/obedience_hormones_overlay"), 0xFFA6724A));
    public static final RegistryObject<FluidType> PARENTAL_HORMONES_FLUID_TYPE = FLUID_TYPES.register("parental_hormones_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/parental_hormones_still"), new ResourceLocation(References.MODID, "block/fluids/parental_hormones_flow"), new ResourceLocation(References.MODID, "block/fluids/parental_hormones_overlay"), 0xFFA672FF));
    public static final RegistryObject<FluidType> COAGULANT_FLUID_TYPE = FLUID_TYPES.register("coagulant_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/coagulant_still"), new ResourceLocation(References.MODID, "block/fluids/coagulant_flow"), new ResourceLocation(References.MODID, "block/fluids/coagulant_overlay"), 0xFFBA10CD));
    public static final RegistryObject<FluidType> SOFTENER_FLUID_TYPE = FLUID_TYPES.register("softener_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/softener_still"), new ResourceLocation(References.MODID, "block/fluids/softener_flow"), new ResourceLocation(References.MODID, "block/fluids/softener_overlay"), 0xFFF4C42F));
    public static final RegistryObject<FluidType> SEDATIVE_FLUID_TYPE = FLUID_TYPES.register("sedative_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/sedative_still"), new ResourceLocation(References.MODID, "block/fluids/sedative_flow"), new ResourceLocation(References.MODID, "block/fluids/sedative_overlay"), 0xFFC13719));
    public static final RegistryObject<FluidType> TEARS_FLUID_TYPE = FLUID_TYPES.register("tears_fluid", () -> new SurgicalFluidType(FluidType.Properties.create().lightLevel(2).density(15).viscosity(5), new ResourceLocation(References.MODID, "block/fluids/tears_still"), new ResourceLocation(References.MODID, "block/fluids/tears_flow"), new ResourceLocation(References.MODID, "block/fluids/tears_overlay"), 0xFFD5DEFF));


    public static final RegistryObject<FlowingFluid> SOURCE_FLUID_SEDATIVE = FLUIDS.register("sedative_fluid_source", () -> new ForgeFlowingFluid.Source(BTVFluids.SEDATIVE_PROPERTIES));
    public static final RegistryObject<FlowingFluid> FLOWING_FLUID_SEDATIVE = FLUIDS.register("sedative_fluid_flowing", () -> new ForgeFlowingFluid.Flowing(BTVFluids.SEDATIVE_PROPERTIES));
    public static final RegistryObject<FlowingFluid> SOURCE_FLUID_SOFTENER = FLUIDS.register("softener_fluid_source", () -> new ForgeFlowingFluid.Source(BTVFluids.SOFTENER_PROPERTIES));
    public static final RegistryObject<FlowingFluid> FLOWING_FLUID_SOFTENER = FLUIDS.register("softener_fluid_flowing", () -> new ForgeFlowingFluid.Flowing(BTVFluids.SOFTENER_PROPERTIES));
    public static final RegistryObject<FlowingFluid> SOURCE_FLUID_COAGULANT = FLUIDS.register("coagulant_fluid_source", () -> new ForgeFlowingFluid.Source(BTVFluids.COAGULANT_PROPERTIES));
    public static final RegistryObject<FlowingFluid> FLOWING_FLUID_COAGULANT = FLUIDS.register("coagulant_fluid_flowing", () -> new ForgeFlowingFluid.Flowing(BTVFluids.COAGULANT_PROPERTIES));
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_MOVEMENT_SPEED_SERUM = registerSourceAndFlowing("movement_speed_serum_fluid", () -> BTVFluids.MOVEMENT_SPEED_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_MOVEMENT_SLOWDOWN_SERUM = registerSourceAndFlowing("movement_slowdown_serum_fluid", () -> BTVFluids.MOVEMENT_SLOWDOWN_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_DIG_SPEED_SERUM = registerSourceAndFlowing("dig_speed_serum_fluid", () -> BTVFluids.DIG_SPEED_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_DIG_SLOWDOWN_SERUM = registerSourceAndFlowing("dig_slowdown_serum_fluid", () -> BTVFluids.DIG_SLOWDOWN_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_DAMAGE_BOOST_SERUM = registerSourceAndFlowing("damage_boost_serum_fluid", () -> BTVFluids.DAMAGE_BOOST_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_HEAL_SERUM = registerSourceAndFlowing("heal_serum_fluid", () -> BTVFluids.HEAL_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_HARM_SERUM = registerSourceAndFlowing("harm_serum_fluid", () -> BTVFluids.HARM_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_JUMP_SERUM = registerSourceAndFlowing("jump_serum_fluid", () -> BTVFluids.JUMP_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_CONFUSION_SERUM = registerSourceAndFlowing("confusion_serum_fluid", () -> BTVFluids.CONFUSION_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_REGENERATION_SERUM = registerSourceAndFlowing("regeneration_serum_fluid", () -> BTVFluids.REGENERATION_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_DAMAGE_RESISTANCE_SERUM = registerSourceAndFlowing("damage_resistance_serum_fluid", () -> BTVFluids.DAMAGE_RESISTANCE_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_FIRE_RESISTANCE_SERUM = registerSourceAndFlowing("fire_resistance_serum_fluid", () -> BTVFluids.FIRE_RESISTANCE_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_WATER_BREATHING_SERUM = registerSourceAndFlowing("water_breathing_serum_fluid", () -> BTVFluids.WATER_BREATHING_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_INVISIBILITY_SERUM = registerSourceAndFlowing("invisibility_serum_fluid", () -> BTVFluids.INVISIBILITY_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_BLINDNESS_SERUM = registerSourceAndFlowing("blindness_serum_fluid", () -> BTVFluids.BLINDNESS_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_NIGHT_VISION_SERUM = registerSourceAndFlowing("night_vision_serum_fluid", () -> BTVFluids.NIGHT_VISION_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_HUNGER_SERUM = registerSourceAndFlowing("hunger_serum_fluid", () -> BTVFluids.HUNGER_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_WEAKNESS_SERUM = registerSourceAndFlowing("weakness_serum_fluid", () -> BTVFluids.WEAKNESS_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_POISON_SERUM = registerSourceAndFlowing("poison_serum_fluid", () -> BTVFluids.POISON_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_WITHER_SERUM = registerSourceAndFlowing("wither_serum_fluid", () -> BTVFluids.WITHER_SERUM_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_MEMORY_HORMONES = registerSourceAndFlowing("memory_hormones_fluid", () -> BTVFluids.MEMORY_HORMONES_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_OBEDIENCE_HORMONES = registerSourceAndFlowing("obedience_hormones_fluid", () -> BTVFluids.OBEDIENCE_HORMONES_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_PARENTAL_HORMONES = registerSourceAndFlowing("parental_hormones_fluid", () -> BTVFluids.PARENTAL_HORMONES_PROPERTIES);
    public static final Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> FLUID_TEARS = registerSourceAndFlowing("tears_fluid", () -> BTVFluids.TEARS_PROPERTIES);

    private static Tuple<RegistryObject<FlowingFluid>, RegistryObject<FlowingFluid>> registerSourceAndFlowing(String name, Supplier<ForgeFlowingFluid.Properties> properties) {
        RegistryObject<FlowingFluid> A = FLUIDS.register(name + "_source", () -> new ForgeFlowingFluid.Source(properties.get()));
        RegistryObject<FlowingFluid> B = FLUIDS.register(name + "_flowing", () -> new ForgeFlowingFluid.Flowing(properties.get()));
        return new Tuple<>(A, B);
    }

    public static final ForgeFlowingFluid.Properties SEDATIVE_PROPERTIES = new ForgeFlowingFluid.Properties(SEDATIVE_FLUID_TYPE, SOURCE_FLUID_SEDATIVE, FLOWING_FLUID_SEDATIVE).slopeFindDistance(2).levelDecreasePerBlock(2).block(Registration.SEDATIVE_BLOCK).bucket(Registration.SEDATIVE_BUCKET);
    public static final ForgeFlowingFluid.Properties COAGULANT_PROPERTIES = new ForgeFlowingFluid.Properties(COAGULANT_FLUID_TYPE, SOURCE_FLUID_COAGULANT, FLOWING_FLUID_COAGULANT).slopeFindDistance(2).levelDecreasePerBlock(2).block(Registration.COAGULANT_BLOCK).bucket(Registration.COAGULANT_BUCKET);
    public static final ForgeFlowingFluid.Properties SOFTENER_PROPERTIES = new ForgeFlowingFluid.Properties(SOFTENER_FLUID_TYPE, SOURCE_FLUID_SOFTENER, FLOWING_FLUID_SOFTENER).slopeFindDistance(2).levelDecreasePerBlock(2).block(Registration.SOFTENER_BLOCK).bucket(Registration.SOFTENER_BUCKET);
    public static final ForgeFlowingFluid.Properties MOVEMENT_SPEED_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(MOVEMENT_SPEED_SERUM_FLUID_TYPE, FLUID_MOVEMENT_SPEED_SERUM.getA(), FLUID_MOVEMENT_SPEED_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.MOVEMENT_SPEED_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties MOVEMENT_SLOWDOWN_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(MOVEMENT_SLOWDOWN_SERUM_FLUID_TYPE, FLUID_MOVEMENT_SLOWDOWN_SERUM.getA(), FLUID_MOVEMENT_SLOWDOWN_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.MOVEMENT_SLOWDOWN_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties DIG_SPEED_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(DIG_SPEED_SERUM_FLUID_TYPE, FLUID_DIG_SPEED_SERUM.getA(), FLUID_DIG_SPEED_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.DIG_SPEED_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties DIG_SLOWDOWN_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(DIG_SLOWDOWN_SERUM_FLUID_TYPE, FLUID_DIG_SLOWDOWN_SERUM.getA(), FLUID_DIG_SLOWDOWN_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.DIG_SLOWDOWN_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties DAMAGE_BOOST_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(DAMAGE_BOOST_SERUM_FLUID_TYPE, FLUID_DAMAGE_BOOST_SERUM.getA(), FLUID_DAMAGE_BOOST_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.DAMAGE_BOOST_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties HEAL_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(HEAL_SERUM_FLUID_TYPE, FLUID_HEAL_SERUM.getA(), FLUID_HEAL_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.HEAL_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties HARM_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(HARM_SERUM_FLUID_TYPE, FLUID_HARM_SERUM.getA(), FLUID_HARM_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.HARM_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties JUMP_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(JUMP_SERUM_FLUID_TYPE, FLUID_JUMP_SERUM.getA(), FLUID_JUMP_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.JUMP_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties CONFUSION_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(CONFUSION_SERUM_FLUID_TYPE, FLUID_CONFUSION_SERUM.getA(), FLUID_CONFUSION_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.CONFUSION_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties REGENERATION_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(REGENERATION_SERUM_FLUID_TYPE, FLUID_REGENERATION_SERUM.getA(), FLUID_REGENERATION_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.REGENERATION_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties DAMAGE_RESISTANCE_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(DAMAGE_RESISTANCE_SERUM_FLUID_TYPE, FLUID_DAMAGE_RESISTANCE_SERUM.getA(), FLUID_DAMAGE_RESISTANCE_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.DAMAGE_RESISTANCE_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties FIRE_RESISTANCE_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(FIRE_RESISTANCE_SERUM_FLUID_TYPE, FLUID_FIRE_RESISTANCE_SERUM.getA(), FLUID_FIRE_RESISTANCE_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.FIRE_RESISTANCE_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties WATER_BREATHING_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(WATER_BREATHING_SERUM_FLUID_TYPE, FLUID_WATER_BREATHING_SERUM.getA(), FLUID_WATER_BREATHING_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.WATER_BREATHING_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties INVISIBILITY_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(INVISIBILITY_SERUM_FLUID_TYPE, FLUID_INVISIBILITY_SERUM.getA(), FLUID_INVISIBILITY_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.INVISIBILITY_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties BLINDNESS_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(BLINDNESS_SERUM_FLUID_TYPE, FLUID_BLINDNESS_SERUM.getA(), FLUID_BLINDNESS_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.BLINDNESS_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties NIGHT_VISION_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(NIGHT_VISION_SERUM_FLUID_TYPE, FLUID_NIGHT_VISION_SERUM.getA(), FLUID_NIGHT_VISION_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.NIGHT_VISION_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties HUNGER_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(HUNGER_SERUM_FLUID_TYPE, FLUID_HUNGER_SERUM.getA(), FLUID_HUNGER_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.HUNGER_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties WEAKNESS_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(WEAKNESS_SERUM_FLUID_TYPE, FLUID_WEAKNESS_SERUM.getA(), FLUID_WEAKNESS_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.WEAKNESS_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties POISON_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(POISON_SERUM_FLUID_TYPE, FLUID_POISON_SERUM.getA(), FLUID_POISON_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.POISON_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties WITHER_SERUM_PROPERTIES = new ForgeFlowingFluid.Properties(WITHER_SERUM_FLUID_TYPE, FLUID_WITHER_SERUM.getA(), FLUID_WITHER_SERUM.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.WITHER_SERUM_FLUID_SERUM_BUCKET);
    public static final ForgeFlowingFluid.Properties MEMORY_HORMONES_PROPERTIES = new ForgeFlowingFluid.Properties(MEMORY_HORMONES_FLUID_TYPE, FLUID_MEMORY_HORMONES.getA(), FLUID_MEMORY_HORMONES.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.MEMORY_HORMONES_FLUID_BUCKET);
    public static final ForgeFlowingFluid.Properties OBEDIENCE_HORMONES_PROPERTIES = new ForgeFlowingFluid.Properties(OBEDIENCE_HORMONES_FLUID_TYPE, FLUID_OBEDIENCE_HORMONES.getA(), FLUID_OBEDIENCE_HORMONES.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.OBEDIENCE_HORMONES_FLUID_BUCKET);
    public static final ForgeFlowingFluid.Properties PARENTAL_HORMONES_PROPERTIES = new ForgeFlowingFluid.Properties(PARENTAL_HORMONES_FLUID_TYPE, FLUID_PARENTAL_HORMONES.getA(), FLUID_PARENTAL_HORMONES.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).bucket(Registration.PARENTAL_HORMONES_FLUID_BUCKET);
    public static final ForgeFlowingFluid.Properties TEARS_PROPERTIES = new ForgeFlowingFluid.Properties(TEARS_FLUID_TYPE, FLUID_TEARS.getA(), FLUID_TEARS.getB()).slopeFindDistance(2).levelDecreasePerBlock(2).block(Registration.TEARS_BLOCK).bucket(Registration.TEARS_FLUID_BUCKET);
}
